name: 'Dart Pull Request Use Case Validator'
description: 'Validates your use cases to have valid class names and methods.'
inputs:
   github-token:
     description: 'GitHub Access Token'
     default: ${{ github.token }}
     required: true
   method-name:
     description: 'Desired public callable method of a use case.'
     required: false
     default: 'run'
outputs:
runs:
  using: 'node16'
  main: 'index.js'
